# Generated by Django 4.2.1 on 2023-06-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Argocore',
            fields=[
                ('platformnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('cyclenumber', models.IntegerField()),
                ('pressure', models.DecimalField(decimal_places=1, max_digits=7)),
                ('cpressure', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('qpressure', models.CharField(blank=True, max_length=1, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('ctemperature', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('qtemperature', models.CharField(blank=True, max_length=1, null=True)),
                ('salinity', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('csalinity', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('qsalinity', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'argocore',
                'db_table_comment': '02 Argo-核心数据表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Argofloat',
            fields=[
                ('platformnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('datecenter', models.TextField(blank=True, null=True)),
                ('lauchdate', models.CharField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('projectname', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'argofloat',
                'db_table_comment': '01 Argo-浮标基础信息表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Argoheader',
            fields=[
                ('platformnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('cyclenumber', models.IntegerField()),
                ('julianday', models.CharField(blank=True, null=True)),
                ('datadate', models.CharField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'argoheader',
                'db_table_comment': '03 Argo-观测次数信息表',
                'managed': False,
            },
        ),
    ]
